In [ ]:
# HYPOTHESIS TESTING : it is a part of statistical analysis where we test the assumptions made regarding a population parameter.
# it is generally used when we were to compare a single group with an external standard and two or more groups with each other.

# TERMINOLOGY USED IN HYPOTHESIS TESTING :
# 1) NULL HYPOTHESIS : null hypothesis is a statistical theory that suggests there is no statistical significance exists between the populations. it is denoted by HO and reads as H-naught.
# EXAMPLE : A=B <=,>=
# 2) ALTERNATIVE HYPOTHESIS : an alternative hypothesis suggests there is a significant difference between the population parameters . it could be greater or smaller. 
#    basically,it is the contrast of the null hypothesis. it is denoted by Ha or H1.
# EXAMPLE : A<B,>,!=

# THERE ARE THREE TYPES OF HYPOTHESIS TESTING : 
# 1) Z-TEST (AVERAGE)
# 2) T-TEST (AVERAGE)
# 3) CHI-SQUARE TEST :
#                      1) CHECK THE GOODNESS
#                     2) RELATION FIND OUT 
    
# STEPS OF HYPOTHESIS TESTING :
# 1) state null(HO) and alternative(H1) hypothesis : HO must always contain equality(=).H1 always contains difference(!=,>,<).
# 2) choose level of significance(a) : 
# 3) find critical values
# 4) find test statistic
# 5) draw your conclusion

In [5]:
import scipy.stats as st
import numpy as np

In [ ]:
# QUESTION : A teacher claims that the mean score of students in his class is greater than 82 with a standard deviation of 20.
#           if a sample of 81 students was selected with a mean score of 90.

In [6]:
st.norm.ppf(0.95)

1.6448536269514722

In [7]:
s_x =90
p_u = 82
p_std = 20
n = 81
ap = 0.05

In [8]:
z_cal =(s_x - p_u)/(p_std/np.sqrt(n))

In [9]:
z_cal

3.5999999999999996

In [10]:
z_table = st.norm.ppf(1-ap)
z_table

1.6448536269514722

In [11]:
if z_table < z_cal :
    print("Ha is right")
else:
    print("Ho is right")

Ha is right


In [ ]:
# QUESTION : Z-TEST
# SCENARIO : Imagin you work for an e commerce company , and your team is responsible for analyzing customer purchase data.
#             you want to determine whether a new website design has led to a significant increase in the average purchase 
#             amount compared to the design.

# DATA : you have collected data form a random sample of 30 customers who made purchase on the old website design and 30 
#        customers who made purchase on the new website design. you have the sample means,sample standard deviations , and sample sizes for both groups.
# OLD DESIGN DATA : [45.2,42.8,38.9,43.5,41.0,40.5,42.7,39.8,41.4,44.3,39.7,42.1,40.8,43.0,42.2,41.5,39.6,44.0,43.1,38.7,43.9,42.0,42.8,43.7,41.3,40.9,42.5,41.6]
# NEW DESIGN DATA : [48.5,49.1,50.2,47.8,48.7,49.9,48.0,50.5,49.8,48.0,50.5,49.8,48.8,48.2,49.9,49.7,50.3,49.4,50.1,48.6,48.3,49.0,50.0,48.4,49.3,49.5,48.8,50.6,50.4,48.1,49.2,50.7,50.8]
# POPULATION = 25
# N = 30

# FORMULA : Z-TEST = mean(new)-mean(old)/(sigma/rootN)

In [12]:
import scipy.stats as st
import numpy as np

In [19]:
Old_design_data = np.array([45.2,42.8,38.9,43.5,41.0,40.5,42.7,39.8,41.4,44.3,39.7,42.1,40.8,43.0,42.2,41.5,39.6,44.0,43.1,38.7,43.9,42.0,42.8,43.7,41.3,40.9,42.5,41.6])
New_design_data = np.array([48.5,49.1,50.2,47.8,48.7,49.9,48.0,50.5,49.8,48.0,50.5,49.8,48.8,48.2,49.9,49.7,50.3,49.4,50.1,48.6,48.3,49.0,50.0,48.4,49.3,49.5,48.8,50.6,50.4,48.1,49.2,50.7,50.8])

In [20]:
pop_std =2.5
n_sp = len(New_design_data)
apl = 0.05

In [21]:
mean_old = np.mean(Old_design_data)
mean_new = np.mean(New_design_data)

In [22]:
z_cal = (mean_new - mean_old)/(pop_std/np.sqrt(n_sp))
z_cal

17.118548004317674

In [23]:
z_table = st.norm.ppf(1-ap)
z_table

1.6448536269514722

In [24]:
if z_cal>z_table:
    print("Ha is right")
else:
    print("Ho is right")

Ha is right


In [ ]:
# T-TEST :
# data ----> normal distribution
# 1) pop --> mean
# 2) sample --> std
#           --> mean
# 3) no. of sample < 30
# 4) formula : mean(x)-mue/(s/root(n))
#    x = sample mean
#    mue = pop mean
#    s = std sample
#    n = no. of sample

In [ ]:
# QUESTION : A manufacture claims that the average weight of a bag of potato chips is 150 grams. A sample of 25 bags is taken, and the 
#           average weight is found to be 148 grams , with a standard deviation of 5 grams.test the manufacturer's claim using a one-tailed t-test with a significance level of 0.05.

# mue = 150                 Ho mue = 150 gm
# mean(x) = 148             Ha mue < 150 gm 
# n = 25
# s = 5 


In [28]:
import scipy.stats as st
import numpy as np

In [26]:
t_table =  st.t.ppf(0.05,24)

-1.7108820799094282

In [ ]:
# QUESTION : A company wants to test whether there is a difference in productivity between two teams.they randomly select 20 employees from each team and record 
#           their productivity scores.the mean productivity score for Team A is 80 with a standard deviation of 5,while the mean productivity score for Team B is 75 
#           with a standard deviation of 6 .test at a 5% level of significance whether there is a difference productivity between the two teams.   

# FORMULA : (mean(a)-mean(b))-(mue(a)-mue(b))/(root(Sa2/na + Sb2/nb))

In [ ]:
# SOLUTION : Ho = P(A)-P(B) = 0
#          : Ha = P(A)-P(B) !=0


In [27]:
t_table =  st.t.ppf(1-0.025,38)
t_table

2.024394164575136

In [29]:
t_cal = (80-75)/(np.sqrt((25/20)+(26/20)))
t_cal

3.1311214554257476

In [ ]:
# QUESTION : A company wants to test whether a new training program improves the typing spped of its employees.the typing spped of 20 employees was recoreded before and after the
#            training program.the data is given below.test at a 5% level of significance whether the traning program has an effect on the typing spped of the employees.

# Before : 50,60,45,65,55,70,40,75,80,65,70,60,50,55,45,75,60,50,65,70.
# after : 60,70,55,75,65,80,50,85,90,70,75,65,55,60,50,80,65,55,70,75.

# Ho : tB-tA=0
# Ha : tB-tA !=0

# FORMULA : x(A)-x(B)/(root(s(A)2/n + s(B)2/n))

In [30]:
t_table =  st.t.ppf(1-0.025,19)
t_table

2.093024054408263

In [31]:
Before =np.array([50,60,45,65,55,70,40,75,80,65,70,60,50,55,45,75,60,50,65,70])
After =np.array([60,70,55,75,65,80,50,85,90,70,75,65,55,60,50,80,65,55,70,75])



In [32]:
std_a = np.std(After)
std_b = np.std(Before)
mean_a = np.mean(After)
mean_b = np.mean(Before)

In [33]:
t_cal = (mean_a-mean_b) / (np.sqrt(((std_a*std_a)/len(After))+((std_b*std_b)/len(Before))))

In [34]:
t_cal

2.061200527128206

In [ ]:
# CHI-TEST :
1) CHI-SQUARE-TEST :
    # FORMULA : CHI SQUARE TEST : SUM(Oi-Ei)2/Ei
    # Oi = observed value 
    # Ei = expected value

In [ ]:
# EXAMPLE : Afair die is rolled 120 times and the following  results are obtained:
#           face 1 : 22 times---->20
#           face 2 : 17 times---->20
#           face 3 : 20 times---->20
#           face 4 : 26 times----->20
#          face 5 : 22 times------>20
#         face 6 : 13 times------->20  
# test at a 5% level of signifivance whether the die is fair.

# Ho die is fair
# Ha die is not fair

In [35]:
ob =np.array([22,17,20,26,22,13])
ex =np.array([20,20,20,20,20,20])

In [36]:
ob - ex

array([ 2, -3,  0,  6,  2, -7])

In [37]:
np.square(ob - ex)

array([ 4,  9,  0, 36,  4, 49])

In [38]:
np.sum(np.square(ob - ex)/ex)

5.1000000000000005

In [ ]:
# EXAMPLE : A study was conducted to investigate whether there is a relationship between gender and the preferred genre of music. A sample of 235 people was selected , and 
#           and the data collected is shown below. test at a 5% level of significance whether there is a significance association between gender and music preference.
#          POP      HIP-HOP   CLASSICAL   ROCK
# MALE     40       45         25          10 -----> sum R1
# FEMALE   35       30         20          30 -----> sum R2

# sum C1 * sum R1/ no. of samples

# Ho = no association
# Ha = association

In [39]:
# OBESERVATION VALUE
row1 = np.array([40,45,25,10])
row2 = np.array([35,30,20,30])

In [40]:
np.sum(row1) + np.sum(row2)

235

In [43]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_row = np.array([sum_r1,sum_r2])
sum_row

array([120, 115])

In [ ]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_r1,sum_r2

In [42]:
sum_cal = row1+row2
sum_cal

array([75, 75, 45, 40])

In [45]:
exp = []
for i in sum_row:
    for j in sum_cal:
        print(i,j)
        value = (i*j)/235
        exp.append(value)

120 75
120 75
120 45
120 40
115 75
115 75
115 45
115 40


In [46]:
exp

[38.297872340425535,
 38.297872340425535,
 22.97872340425532,
 20.425531914893618,
 36.702127659574465,
 36.702127659574465,
 22.02127659574468,
 19.574468085106382]

In [47]:
obj = np.array([40,45,25,10,35,30,20,30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [49]:
len(obj)

8

In [50]:
len(exp)

8

In [48]:
obj - exp

array([  1.70212766,   6.70212766,   2.0212766 , -10.42553191,
        -1.70212766,  -6.70212766,  -2.0212766 ,  10.42553191])

In [51]:
np.square(obj - exp)

array([  2.89723857,  44.91851517,   4.08555908, 108.69171571,
         2.89723857,  44.91851517,   4.08555908, 108.69171571])

In [53]:
np.square(obj - exp)/exp

array([0.07565012, 1.17287234, 0.17779748, 5.32136525, 0.07893925,
       1.22386679, 0.1855278 , 5.55272895])